#spring.application.name=basedatos

spring:
  application:
    name: 'basedatos'
  datasource:
    url: 'jdbc:mysql://localhost:3306/sodimac2?useSSL=false&serverTimezone=UTC'
    username: 'root'
    password: 'Yoselin!0709'
    driver-class-name: 'com.mysql.cj.jdbc.Driver'
  jpa:
    show-sql: true
    database-platform: 'org.hibernate.dialect.MySQLDialect'
    generate-ddt: true
    hibernate:
      ddl-auto: create
    open-in-view: false
